#!/usr/bin/env python
#++
# % smtp_logger(1)	Infinity utilities
#
# # NAME
#
# smtp_logger - SMTP logger that saves e-mails
#
# # SYNOPSIS
#
# **smtp_logger**
#
# # DESCRIPTION
#
# Accepts RFC2822 messages and saves to a file.
#
# This script is meant to be executed as a systemd(1) unit
# and configured through environment files (using
# EnvironmentFile)
#
# # ENVIRONMENT
#
# * SMTP_ALLOWED : List of IP addresses allowed
# * SMTP_LISTEN : IP address to bind
# * SMTP_PORT : Port to use
# * LOG_DIR : Log directory
#
# # FILES
#
# * /etc/smtp_logger.config - Configuration environment
#
#--
#<<
# % index#sl
# - smtp_logger - SMTP logger
#>>
#
#   Copyright (C) 2018 Alejandro Liu Ly
#
#   This is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as
#   published by the Free Software Foundation; either version 2 of 
#   the License, or (at your option) any later version.
#
#   This software is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public
#   License along with this program.  If not, see 
#   <http://www.gnu.org/licenses/>
#

import asyncore
from smtpd import SMTPServer
import fnmatch
import os

#from email.parser import Parser
#from pprint import pprint
#from datetime import datetime

allow_list = os.environ['SMTP_ALLOWED'].split(",")
LOG_DIR = os.environm['LOG_DIR']
      

from datetime import datetime
import asyncore
from smtpd import SMTPServer

class EmlServer(SMTPServer):
  no = 0
  def process_message(self, peer, mailfrom, rcpttos, data):
    peer_ip = peer[0]
    allowed = 0
    
    for rule in allow_list:
      if fnmatch.fnmatch(peer_ip,rule):
	allowed = 1
	break
    
    if not allowed :
      print 'Peer :%s is not allowed' % peer_ip
      return
    filename = '%s/%s-%d.eml' % LOG_DIR, (datetime.now().strftime('%Y%m%d%H%M%S'),
	    self.no)
    f = open(filename, 'w')
    f.write(data)
    f.close
    print '%s saved.' % filename
    self.no += 1

def run():
  foo = EmlServer((os.environ['SMTP_LISTEN'], int(os.environ['SMTP_PORT'])), None)
  try:
    asyncore.loop()
  except KeyboardInterrupt:
    pass

if __name__ == '__main__':
  run()
